// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HTMLTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hTML() {
    // Test name: HTML
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com.br/");
    // 2 | setWindowSize | 1050x708 | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | sendKeys | name=q | ${KEY_DOWN}
    driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
    // 4 | type | name=q | html formatter
    driver.findElement(By.name("q")).sendKeys("html formatter");
    // 5 | sendKeys | name=q | ${KEY_ENTER}
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 6 | click | css=.MjjYud:nth-child(2) .LC20lb | 
    driver.findElement(By.cssSelector(".MjjYud:nth-child(2) .LC20lb")).click();
    // 7 | click | linkText=XML | 
    driver.findElement(By.linkText("XML")).click();
    // 8 | click | linkText=CSS | 
    driver.findElement(By.linkText("CSS")).click();
    // 9 | click | linkText=JavaScript | 
    driver.findElement(By.linkText("JavaScript")).click();
    // 10 | click | linkText=PHP | 
    driver.findElement(By.linkText("PHP")).click();
    // 11 | click | linkText=JSON | 
    driver.findElement(By.linkText("JSON")).click();
  }
}
